services:
  orientdb:
    image: orientdb:3.0
    container_name: orientdb
    ports:
      - '2424:2424'
      - '2480:2480'
    environment:
      ORIENTDB_ROOT_PASSWORD: ${ORIENTDB_ROOT_PASSWORD}
    volumes:
      # - <config_path>:/orientdb/config
      - ./db/data:/orientdb/databases
      - ./db/data-backup:/orientdb/backup
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:2480']
      interval: 15s
      timeout: 10s
      retries: 5

  nginx-local:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx-local
    ports:
      - '5500:5500'
    depends_on:
      orientdb:
        condition: service_healthy
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf
