services:
  orientdb:
    image: orientdb:3.0
    container_name: orientdb
    ports:
      - '2424:2424'
      - '2480:2480'
    environment:
      ORIENTDB_ROOT_PASSWORD: ${ORIENTDB_ROOT_PASSWORD}

    volumes:
      # - <config_path>:/orientdb/config
      - ./db/data:/orientdb/databases
      - ./db/data-backup:/orientdb/backup
